config/routes.rb
Rails.application.routes.draw do

  resources :scores
  resources :enologists
  resources :wine_strains
  resources :wines
  resources :strains
  
    devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/enologist.rb
class Enologist < ApplicationRecord
  belongs_to :user
end

app/controllers/enologists_controller.rb
class EnologistsController < ApplicationController
  before_action :set_enologist, only: %i[ show edit update destroy ]

  # GET /enologists or /enologists.json
  def index
    @enologists = Enologist.all
  end

  # GET /enologists/1 or /enologists/1.json
  def show
  end

  # GET /enologists/new
  def new
    @enologist = Enologist.new
  end

  # GET /enologists/1/edit
  def edit
  end

  # POST /enologists or /enologists.json
  def create
    @enologist = Enologist.new(enologist_params)

    respond_to do |format|
      if @enologist.save
        format.html { redirect_to enologist_url(@enologist), notice: "Enologist was successfully created." }
        format.json { render :show, status: :created, location: @enologist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @enologist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enologists/1 or /enologists/1.json
  def update
    respond_to do |format|
      if @enologist.update(enologist_params)
        format.html { redirect_to enologist_url(@enologist), notice: "Enologist was successfully updated." }
        format.json { render :show, status: :ok, location: @enologist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @enologist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enologists/1 or /enologists/1.json
  def destroy
    @enologist.destroy

    respond_to do |format|
      format.html { redirect_to enologists_url, notice: "Enologist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enologist
      @enologist = Enologist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def enologist_params
      params.require(:enologist).permit(:type, :age, :nationality, :company, :user_id)
    end
end

app/helpers/enologists_helper.rb
module EnologistsHelper
end

app/views/enologists/_enologist.html.erb
<div id="<%= dom_id enologist %>">
  <p>
    <strong>Type:</strong>
    <%= enologist.type %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= enologist.age %>
  </p>

  <p>
    <strong>Nationality:</strong>
    <%= enologist.nationality %>
  </p>

  <p>
    <strong>Company:</strong>
    <%= enologist.company %>
  </p>

  <p>
    <strong>User:</strong>
    <%= enologist.user_id %>
  </p>

</div>

app/views/enologists/_form.html.erb
<%= form_with(model: enologist) do |form| %>
  <% if enologist.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(enologist.errors.count, "error") %> prohibited this enologist from being saved:</h2>

      <ul>
        <% enologist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :type, style: "display: block" %>
    <%= form.text_field :type %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :nationality, style: "display: block" %>
    <%= form.text_field :nationality %>
  </div>

  <div>
    <%= form.label :company, style: "display: block" %>
    <%= form.text_field :company %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/enologists/edit.html.erb
<h1>Editing enologist</h1>

<%= render "form", enologist: @enologist %>

<br>

<div>
  <%= link_to "Show this enologist", @enologist %> |
  <%= link_to "Back to enologists", enologists_path %>
</div>

app/views/enologists/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Enologists</h1>

<div id="enologists">
  <% @enologists.each do |enologist| %>
    <%= render enologist %>
    <p>
      <%= link_to "Show this enologist", enologist %>
    </p>
  <% end %>
</div>

<%= link_to "New enologist", new_enologist_path %>

app/views/enologists/new.html.erb
<h1>New enologist</h1>

<%= render "form", enologist: @enologist %>

<br>

<div>
  <%= link_to "Back to enologists", enologists_path %>
</div>

app/views/enologists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @enologist %>

<div>
  <%= link_to "Edit this enologist", edit_enologist_path(@enologist) %> |
  <%= link_to "Back to enologists", enologists_path %>

  <%= button_to "Destroy this enologist", @enologist, method: :delete %>
</div>