config/routes.rb
Rails.application.routes.draw do

  resources :scores
  resources :enologists
  resources :wine_strains
  resources :wines
  resources :strains
  
    devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_admin_session.html.erb
<% if current_user.has_role? :admin %>
       
  <li class="nav navbar-nav dropdown "> 
    <a class=" dropdown-toggle text-light text-decoration-none " style="list-style-type: none;"  href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
       <%= current_user.roles.pluck(:name) %>
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
      
      <li><%= link_to "Nuevo Enologo", new_enologist_path, class:"dropdown-item"%>
      <li><%= link_to "Nueva Cepa", new_strain_path, class:"dropdown-item"%>
      <li><%= link_to "Nuevo Vino", new_wine_path, class:"dropdown-item"%>
      <li><%= link_to "Calificar Vino", new_score_path, class:"dropdown-item"%>
    </ul>
  </li>
<% else %>
    <li class="nav navbar-nav  dropdown "> 
        <a class=" dropdown-toggle text-light text-decoration-none " style="list-style-type: none;"  href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
           <%= current_user.roles.pluck(:name) %>
        </a>
        <ul class="dropdown-menu " aria-labelledby="navbarDropdown">  
           <%= link_to "vinos", wines_path, class:"nav-link active  " %>
           <%= link_to "Calificar Vino", new_score_path, class:"nav-link active  " %>
          
        </ul>
    </li>
 <% end %>

app/views/home/_alerts.html.erb
<% if notice %>
    <p class="notice"><%= notice %></p>
    
<% else alert %>    
    <p class="alert"><%= alert %></p>

<% end %>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
   <div class="container-fluid">
     <%= link_to "Vinos 2", root_path, class:"navbar-brand fs-1"%>
      <div class="navbar text-light dropdown">
           <%=render 'home/session_manager',class:"nav-link  navbar-dark bg-dark"%>
       </div>
     <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
     </button>
     <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">         <li class="nav-item">
         <li class="nav-item">
         <%= link_to "Inicio", root_path, class:"nav-link active fw-light" %>
         </li>
        
         <li class="nav-item">
           <%= link_to "vinos", wines_path , class:"nav-link active fw-light" %>
         </li>

         </li>
     </div>

   </div>
 </nav

app/views/home/_session_manager.html.erb
<% if current_user %>
  <%= render 'home/admin_session' %>
  <li class="nav navbar-nav dropdown "> 
    <a class=" dropdown-toggle text-light text-decoration-none " style="list-style-type: none;"  href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
       <%= current_user.name %> 
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
      
      <li><%= link_to "Editar my cuenta", edit_user_registration_path, class:"dropdown-item"%>

      <li><hr class="dropdown-divider"></li>
      <li><%= button_to "Salir", destroy_user_session_path, method: :delete, class:"dropdown-item active fw-light" %></li>
    </ul>
  </li>
<% else %>
    <li class="nav navbar-nav  dropdown "> 
        <a class=" dropdown-toggle text-light text-decoration-none " style="list-style-type: none;"  href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
           No has ingresado
        </a>
        <ul class="dropdown-menu " aria-labelledby="navbarDropdown">  
           <%= link_to "Sign up", new_user_registration_path, class:"nav-link active  " %>
           <%= link_to "Login", new_user_session_path, class:"nav-link active  " %>
        </ul>
    </li>
 <% end %>

app/views/home/index.html.erb
<h1>Vinos 2</h1>
<p></p>