config/routes.rb
Rails.application.routes.draw do

  resources :scores
  resources :enologists
  resources :wine_strains
  resources :wines
  resources :strains
  
    devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/strain.rb
class Strain < ApplicationRecord
    has_many :wine_strains
    has_many :wines, through: :wine_strains
end

app/controllers/strains_controller.rb
class StrainsController < ApplicationController
  before_action :set_strain, only: %i[ show edit update destroy ]


  # GET /strains or /strains.json
  def index
    @strains = Strain.all
  end

  # GET /strains/1 or /strains/1.json
  def show
  end

  # GET /strains/new
  def new
    @strain = Strain.new
  end

  # GET /strains/1/edit
  def edit
  end

  # POST /strains or /strains.json
  def create
    @strain = Strain.new(strain_params)

    respond_to do |format|
      if @strain.save
        format.html { redirect_to strain_url(@strain), notice: "Strain was successfully created." }
        format.json { render :show, status: :created, location: @strain }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @strain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /strains/1 or /strains/1.json
  def update
    respond_to do |format|
      if @strain.update(strain_params)
        format.html { redirect_to strain_url(@strain), notice: "Strain was successfully updated." }
        format.json { render :show, status: :ok, location: @strain }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @strain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /strains/1 or /strains/1.json
  def destroy
    @strain.destroy

    respond_to do |format|
      format.html { redirect_to strains_url, notice: "Strain was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_strain
      @strain = Strain.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def strain_params
      params.require(:strain).permit(:name)
    end
end

app/helpers/strains_helper.rb
module StrainsHelper
end

app/views/strains/_form.html.erb
<%= form_with(model: strain) do |form| %>
  <% if strain.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(strain.errors.count, "error") %> prohibited this strain from being saved:</h2>

      <ul>
        <% strain.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/strains/_strain.html.erb
<div id="<%= dom_id strain %>">
  <p>
    <strong>Name:</strong>
    <%= strain.name %>
  </p>

</div>

app/views/strains/edit.html.erb
<h1>Editing strain</h1>

<%= render "form", strain: @strain %>

<br>

<div>
  <%= link_to "Show this strain", @strain %> |
  <%= link_to "Back to strains", strains_path %>
</div>

app/views/strains/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Strains</h1>

<div id="strains">
  <% @strains.each do |strain| %>
    <%= render strain %>
    <p>
      <%= link_to "Show this strain", strain %>
    </p>
  <% end %>
</div>

<%= link_to "New strain", new_strain_path %>

app/views/strains/new.html.erb
<h1>New strain</h1>

<%= render "form", strain: @strain %>

<br>

<div>
  <%= link_to "Back to strains", strains_path %>
</div>

app/views/strains/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @strain %>

<div>
  <%= link_to "Edit this strain", edit_strain_path(@strain) %> |
  <%= link_to "Back to strains", strains_path %>

  <%= button_to "Destroy this strain", @strain, method: :delete %>
</div>